name: AWS continuous deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: npm ci
      - run: npm run build
      

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GITKEY }}

      - name: Add remote host to known_hosts
        env:
          REMOTE_USER: ubuntu
          REMOTE_HOST: ec2-13-126-94-218.ap-south-1.compute.amazonaws.com
          REMOTE_DIR: /var/www/html
        run: |
          mkdir -p ~/.ssh
          # ssh-keyscan $REMOTE_HOST >> ~/.ssh/known_hosts
          ssh-keyscan -H -t rsa $REMOTE_HOST  >> ~/.ssh/known_hosts
          
      - name: Copy files via SCP
        run: |
          scp -r ./build/* $REMOTE_USER@$REMOTE_HOST:$REMOTE_DIR
        env:
          SSH_KEY: ${{ secrets.GITKEY }}
