name: Deploy to Nginx Server

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.GITKEY }}

    - name: Copy files via SCP
      env:
        REMOTE_USER: ubuntu
        REMOTE_HOST: 13.201.81.158
        REMOTE_DIR: /var/www/html  # Change to your web root directory
      run: |
        scp -r ./* $REMOTE_USER@$REMOTE_HOST:$REMOTE_DIR
